name: Release on Tag

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'  # Match tags starting with 'v'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Make create_deb.sh executable
      run: chmod +x create_deb.sh

    - name: Set up package_version
      id: package_version
      run: echo "::set-output name=package_version::$(cat create_deb.sh | grep -oP 'package_version="(\d+\.\d+\.\d+)"' | cut -d'"' -f 2)"

    - name: Set environment variables from GitHub Action environment
      run: |
        export PACKAGE_NAME="aws-sam-cli"
        export PACKAGE_VERSION="${{ steps.package_version.outputs.package_version }}"
        export PACKAGE_DESCRIPTION="AWS SAM CLI"
        export MAINTAINER="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"

    - name: Check if Release Already Exists
      id: check_release
      run: |
        package_name="aws-sam-cli"
        package_version="${{ steps.package_version.outputs.package_version }}"
        release_check=$(gh release view "$package_version" 2>&1)
        echo "::set-output name=release_exists::true"
      continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      id: create_release
      run: |
        package_name="aws-sam-cli"
        package_version="${{ steps.package_version.outputs.package_version }}"
        
        # Check if the release already exists
        if [[ "${{ steps.check_release.outputs.release_exists }}" != "true" ]]; then
          echo "Creating release for $package_name v$package_version"
          gh release create "$package_version" "create_deb.sh" --title "Release $package_name v$package_version"
        else
          echo "Release $package_name v$package_version already exists. Skipping release creation."
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Upload Release Asset
      run: |
        package_name="aws-sam-cli"
        package_version="${{ steps.package_version.outputs.package_version }}"
        
        # Upload the .deb package as a release asset
        gh release upload "$package_version" "aws-sam-cli-$package_version.deb" --clobber
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}